apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flask
namespace: hong-lab  

commonLabels:
  logging: elasticsearch

resources:
- deployment.yaml
- service.yaml
- configMap.yaml