apiVersion: apps/v1
kind: Deployment
metadata:
  name: local_library-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local_library
  template:
    metadata:
      labels:
        app: local_library
    spec:
      containers:
        - name: local_library-container
          image: focal1119/local_library_website:dev
          ports:
            - containerPort: 8000
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80